name: Update Stats

on:
  schedule:
    # Her gün gece 00:00'da çalış (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Manuel tetikleme için buton ekler

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Dosyayı repoya kaydetmek için izin gerekli

    steps:
      - name: Repoyu Çek
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yükle
        run: pip install requests

      - name: Scripti Çalıştır
        run: python stats.py

      - name: Değişiklikleri Kaydet (Commit & Push)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add my-custom-stats.svg
          git commit -m "İstatistikler güncellendi" || echo "Değişiklik yok"
          git push
